all:
  hosts:
    node1:
      ansible_host: 34.76.137.104
      ip: 10.0.0.2
      ansible_become: yes
      ansible_user: ubuntu
    node2:
      ansible_host: 35.240.88.48
      ip: 10.0.0.3
      ansible_become: yes
      ansible_user: ubuntu
    node3:
      ansible_host: 104.199.96.39
      ip: 10.0.0.4
      ansible_become: yes
      ansible_user: ubuntu
  children:
    kube-master:
      hosts:
        node1:
        node2:
        node3:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node: