#- hosts: all
#  tasks:
#    - name: Install openshift
#      pip:
#        name: openshift

- hosts: node1
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: cc-k8s
        api_version: v1
        kind: Namespace
        state: present
    - name: Deploy Fronted
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Deployment
          metadata:
            namespace: cc-k8s
            name: frontend-site
            labels:
              app: cc-app
          spec:
            replicas: 4
            selector:
              matchLabels:
                app: cc-app
                tier: frontend
                track: stable
            template:
              metadata:
                labels:
                  app: cc-app
                  tier: frontend
                  track: stable
              spec:
                containers:
                  - name: frontend-image
                    image: dsl89/cloudcomputing-ws2021:frontend
                    ports:
                      - containerPort: 80
                    readinessProbe:
                      tcpSocket:
                        port: 80
                        path: /ready
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    livenessProbe:
                      tcpSocket:
                        port: 80
                        path: /ready
                      initialDelaySeconds: 15
                      periodSeconds: 20
    - name: Deploy Backend
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Deployment
          metadata:
            namespace: cc-k8s
            name: backend-site
            labels:
              app: cc-app
          spec:
            replicas: 6
            selector:
              matchLabels:
                app: cc-app
                tier: backend
                track: stable
            template:
              metadata:
                labels:
                  app: cc-app
                  tier: backend
                  track: stable
              spec:
                containers:
                  - name: cc-app
                    image: dsl89/cloudcomputing-ws2021:backend
                    ports:
                      - containerPort: 80
                    readinessProbe:
                      tcpSocket:
                        port: 80
                        path: /ready
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    livenessProbe:
                      tcpSocket:
                        port: 80
                        path: /ready
                      initialDelaySeconds: 15
                      periodSeconds: 20
    - name: Frontend Service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: cc-k8s
            name: cc-frontend-service
          spec:
            selector:
              app: cc-app
              tier: frontend
            ports:
              - protocol: "TCP"
                port: 80
                targetPort: 80
            type: NodePort
    - name: Backend Service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: cc-k8s
            name: cc-backend-service
          spec:
            selector:
              app: cc-app
              tier: backend
            ports:
              - protocol: "TCP"
                port: 80
                targetPort: 80
            type: ClusterIP
